
import java.util.Arrays;
import static javax.swing.JOptionPane.showMessageDialog;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Angel
 */
public class Ventana extends javax.swing.JFrame {

    private static final String anc = "El arreglo no ha sido creado";
    private static final String piun = "Por favor Inserta un número";

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        m = (javax.swing.table.DefaultTableModel) jTDato.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        tFTamanio = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tFDato = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnInicializar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDato = new javax.swing.JTable();
        btnSacar = new javax.swing.JButton();
        btnOrdenarBurbuja = new javax.swing.JButton();
        lblOrdenar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnBusquedaBinaria = new javax.swing.JButton();
        tFBusquedaBinaria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(380, 460));
        setMinimumSize(new java.awt.Dimension(380, 460));
        setPreferredSize(new java.awt.Dimension(380, 460));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Tamaño");
        jLabel1.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 5);
        getContentPane().add(jLabel1, gridBagConstraints);

        tFTamanio.setPreferredSize(new java.awt.Dimension(60, 20));
        tFTamanio.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 5);
        getContentPane().add(tFTamanio, gridBagConstraints);

        btnCrear.setText("Crear");
        btnCrear.setVerifyInputWhenFocusTarget(false);
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 5);
        getContentPane().add(btnCrear, gridBagConstraints);

        jLabel2.setText("Dato");
        jLabel2.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        getContentPane().add(jLabel2, gridBagConstraints);

        tFDato.setPreferredSize(new java.awt.Dimension(60, 20));
        tFDato.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        getContentPane().add(tFDato, gridBagConstraints);

        btnInsertar.setText("Insertar");
        btnInsertar.setVerifyInputWhenFocusTarget(false);
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        getContentPane().add(btnInsertar, gridBagConstraints);

        btnInicializar.setText("Inicializar");
        btnInicializar.setVerifyInputWhenFocusTarget(false);
        btnInicializar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicializarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 5);
        getContentPane().add(btnInicializar, gridBagConstraints);

        btnMostrar.setText("Mostrar");
        btnMostrar.setVerifyInputWhenFocusTarget(false);
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        getContentPane().add(btnMostrar, gridBagConstraints);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane1.setVerifyInputWhenFocusTarget(false);

        jTDato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dato"
            }
        ));
        jScrollPane1.setViewportView(jTDato);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipady = 42;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        btnSacar.setText("Sacar");
        btnSacar.setVerifyInputWhenFocusTarget(false);
        btnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(btnSacar, gridBagConstraints);

        btnOrdenarBurbuja.setText("Ordenar");
        btnOrdenarBurbuja.setVerifyInputWhenFocusTarget(false);
        btnOrdenarBurbuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarBurbujaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(btnOrdenarBurbuja, gridBagConstraints);

        lblOrdenar.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(lblOrdenar, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 150;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        btnBusquedaBinaria.setText("Buscar");
        btnBusquedaBinaria.setVerifyInputWhenFocusTarget(false);
        btnBusquedaBinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaBinariaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(btnBusquedaBinaria, gridBagConstraints);

        tFBusquedaBinaria.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        getContentPane().add(tFBusquedaBinaria, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrdenarBurbujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarBurbujaActionPerformed
        try {
            jPanel1.removeAll();
            XYSeries serie = new XYSeries("Coste");
            lblOrdenar.setText(a.ordenar()+"");
            for (int i = 0; i < a.getTope() - 1; i++) {
                 serie.add(i, 6*i*i-9*i+7);
            }
            XYSeriesCollection collection = new XYSeriesCollection();
            collection.addSeries(serie);
            JFreeChart oChart = ChartFactory.createXYLineChart("Coste","Col","Ren",collection);
            ChartPanel pan = new ChartPanel(oChart);
            jPanel1.setLayout(new java.awt.BorderLayout());
            jPanel1.add(pan);
            jPanel1.validate();
            btnMostrarActionPerformed(null);
        } catch (NullPointerException e) {
            showMessageDialog(this, anc);
        }
    }//GEN-LAST:event_btnOrdenarBurbujaActionPerformed

    private void btnBusquedaBinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaBinariaActionPerformed
        try {
            int pos;
            showMessageDialog(this,((pos = a.busquedaBinaria(Integer.parseInt(tFBusquedaBinaria.getText()))) == -1)?"El número no ha sido encontrado":"El número ha sido encontrado en la posición "+pos);
            btnMostrarActionPerformed(null);
        } catch (NullPointerException e) {
            showMessageDialog(this, anc);
        } catch (NumberFormatException e) {
            showMessageDialog(this, piun + " entero");
        }
    }//GEN-LAST:event_btnBusquedaBinariaActionPerformed

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSacarActionPerformed
        try {
            a.sacar();
            m.removeRow(m.getRowCount() - 1);
        } catch (Exception e) {
            showMessageDialog(this, e.getMessage());
        }
    }// GEN-LAST:event_btnSacarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInsertarActionPerformed
        try {
            a.insertar(Integer.parseInt(tFDato.getText()));
            tFDato.setText("");
            tFDato.requestFocus();
            Object[] x = {a.getA()[a.getTope() - 1]};
            m.addRow(x);

        } catch (NullPointerException e) {
            showMessageDialog(this, anc);
        } catch (NumberFormatException e) {
            showMessageDialog(this, piun + " entero");
        } catch (Exception e) {
            showMessageDialog(this, e.getMessage());
        }
    }// GEN-LAST:event_btnInsertarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCrearActionPerformed
        try {
            a = new ArrayEntero(Integer.parseInt(tFTamanio.getText()));
            tFTamanio.setText("");
            btnMostrarActionPerformed(null);
        } catch (NegativeArraySizeException e) {
            showMessageDialog(this, piun + " entero válido (positivo)");
        } catch (NumberFormatException e) {
            showMessageDialog(this, piun + " entero");
        }
    }// GEN-LAST:event_btnCrearActionPerformed

    private void btnInicializarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInicializarActionPerformed
        try {
            a.inicializar();
            btnMostrarActionPerformed(null);
        } catch (Exception e) {
            showMessageDialog(this, anc);
        }
    }// GEN-LAST:event_btnInicializarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMostrarActionPerformed
        try {
            m.setRowCount(0);
            for (int c = 0; c < a.getTope(); c++) {
                Object vector[] = new Object[1];
                vector[0] = a.getA()[c];
                m.addRow(vector);
            }
        } catch (NullPointerException e) {
            showMessageDialog(this, anc);
        }
    }// GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
//*******************************  ?????????? Esto fue lo que encontre de primera
public void buscar(){
     //int BuscarNm=0;
        int areglo[]=a.getA();
        Arrays.binarySearch(a.getA(),15);//  http://lineadecodigo.com/java/busqueda-binaria-con-java/ busque aqui xd
        if (Arrays.binarySearch(areglo, 15)>0)
                    showMessageDialog(this,"El número " + 15 + " está en el Array");
        else 
                    showMessageDialog(this,"El número " + 15 + " NO está en el Array");
                    showMessageDialog(this,areglo);
}//*************************************???????????
    
    private javax.swing.table.DefaultTableModel m;
    private ArrayEntero a;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusquedaBinaria;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnInicializar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnOrdenarBurbuja;
    private javax.swing.JButton btnSacar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTDato;
    private javax.swing.JLabel lblOrdenar;
    private javax.swing.JTextField tFBusquedaBinaria;
    private javax.swing.JTextField tFDato;
    private javax.swing.JTextField tFTamanio;
    // End of variables declaration//GEN-END:variables
}
